# ----------------------------------------------------------------------------
#
# Package             : kie-cloud-operator
# Source Repo         : https://github.com/kiegroup/kie-cloud-operator
# Travis Job Link     : https://travis-ci.com/github/nagesh4193/kie-cloud-operator/builds/216914199
# Created travis.yml  : Yes
# Maintainer          : Nageswara Rao K<nagesh4193@gmail.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: go

arch:
  - amd64
  - ppc64le

go: 
 - 1.14.x
 - 1.15.x

script:
 - go test -v ./...
