# ----------------------------------------------------------------------------
#
# Package             : loopback-explorer
# Source Repo         :https://github.com/strongloop/loopback-component-explorer.git
# Travis Job Link     : https://travis-ci.com/github/genisysram/loopback-component-explorer/jobs/465739834/config
# Created travis.yml  : No
# Maintainer          : <ramakrishna.s@genisys-group.com>,<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------



sudo: false
arch:
    - amd64
    - ppc64le
language: node_js
node_js:
  - "8"
  - "10"
  - "12"
