# ----------------------------------------------------------------------------
#
# Package             : overrides
# Source Repo         : https://github.com/tlrobinson/overrides
# Travis Job Link     : https://travis-ci.com/github/asellappen/overrides/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - '14'
  - '15'
