# ----------------------------------------------------------------------------
# # Package             : bluebird 
# # Source Repo         : https://github.com/petkaantonov/bluebird.git 
# # Travis Job Link     : https://travis-ci.com/github/sanjaymsh/bluebird/builds/213266891
# # Created travis.yml  : No
# # Maintainer          : Sanjay Mishra <snjkmr32@gmail.com>
# # Script License      : Apache License, Version 2 or later
# # ----------------------------------------------------------------------------

language: node_js
sudo: false
matrix:
    include:
      - node_js: "0.10"
      - node_js: "0.12"
      - node_js: "4"
      - node_js: "5"
      - node_js: "6"
        arch: amd64
      - node_js: "7"
        arch: amd64
      - node_js: "8"
        arch: amd64
      - node_js: "10"
        arch: amd64
      - node_js: "8"
        arch: ppc64le
      - node_js: "10"
        arch: ppc64le
   fast_finish: true
      allow-failures:
         - node_js: "0.10"
         - node_js: "0.12"
         - node_js: "4"
         - node_js: "5"


git:
  depth: 5
env:
  - "NODE_FLAGS='--expose-gc' SCRIPT_FLAGS=''"

before_script:
   - git submodule update --init --recursive
script: 
   - node $NODE_FLAGS tools/test.js $SCRIPT_FLAGS
branches:
    only:
       - master
cache:
   directories:
       - "$HOME/.npm"
