# ----------------------------------------------------------------------------
#
# Package             : crossplane
# Source Repo         : https://github.com/crossplane/crossplane.git
# Travis Job Link     : https://www.travis-ci.com/github/rajesh-ibm-power/crossplane
# Created travis.yml  : Yes
# Maintainer          : Rajesh kumar <Rajesh.kumar13@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ---

language: go
arch:
  - amd64
  - ppc64le
go: 
 - 1.15.6
 - tip

script:
 - go test -v ./...
