# ----------------------------------------------------------------------------
#
# Package             : flask
# Source Repo         : https://github.com/pallets/flask
# Travis Job Link     : https://travis-ci.com/github/nageshlop/flask/builds/217501476
# Created travis.yml  : Yes
# Maintainer          : Nagesh Tarale <Nagesh.Tarale@ibm.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------
language: python

dist: xenial

arch: 
  - amd64
  - ppc64le

python:
  - 3.8

script:
  - python setup.py install
  - python setup.py test 
