# ----------------------------------------------------------------------------
#
# Package             : pyramid_chameleon
# Source Repo         : https://github.com/Pylons/pyramid_chameleon
# Travis Job Link     : https://travis-ci.com/github/asellappen/pyramid_chameleon/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
# Wire up travis
language: python
sudo: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
    - python: 3.8-dev
      env: TOXENV=py38
      dist: xenial
      sudo: true
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3
    - python: 3.5
      env: TOXENV=py2-cover,py3-cover,coverage
    - python: 3.5
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=py27
      arch: ppc64le
    - python: 3.4
      env: TOXENV=py34
      arch: ppc64le     
    - python: 3.5
      env: TOXENV=py35
      arch: ppc64le
    - python: 3.6
      env: TOXENV=py36
      arch: ppc64le
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      arch: ppc64le
      sudo: true
    - python: 3.8-dev
      env: TOXENV=py38
      dist: xenial
      sudo: true
      arch: ppc64le
    - python: 3.5
      env: TOXENV=py2-cover,py3-cover,coverage
      arch: ppc64le
    - python: 3.5
      env: TOXENV=docs
      arch: ppc64le

  allow_failures:
    - env: TOXENV=pypy3
    - env: TOXENV=py38
    - env: TOXENV=py2-cover,py3-cover,coverage

install:
  - travis_retry pip install tox

script:
  - travis_retry tox
