# ----------------------------------------------------------------------------
#
# Package             : react-router
# Source Repo         : https://github.com/ReactTraining/react-router
# Travis Job Link     : https://travis-ci.com/github/dthadi3/react-router/builds/210998601
# Created travis.yml  : No
# Maintainer          : Devendranath Thadi <devendranath.thadi3@gmail.com>
#
# Script License      : Apache 2.0
#
# ----------------------------------------------------------------------------

language: node_js
node_js: node
cache: yarn
jobs:
  include:
  - stage: Test
    env: TEST_ENV=source
    arch: amd64
    before_script:
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - cd packages/react-router && BUILD_ENV=cjs yarn build && cd -
    script: yarn test
  - env: TEST_ENV=cjs BUILD_ENV=cjs
    arch: amd64
    before_script: yarn build
    script: yarn test
  - env: TEST_ENV=umd BUILD_ENV=umd
This conversation was marked as resolved by dthadi3
    arch: amd64
    before_script:
    # react-router ESM build is imported by react-router-dom UMD,
    # so we need to build it before building react-router-dom UMD
    - cd packages/react-router && BUILD_ENV=esm yarn build && cd -
    - yarn build
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - cd packages/react-router && BUILD_ENV=cjs yarn build && cd -
    script: yarn test
#Added power jobs
  - env: TEST_ENV=source
    arch: ppc64le
    before_script:
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - cd packages/react-router && BUILD_ENV=cjs yarn build && cd -
    script: yarn test
  - env: TEST_ENV=cjs BUILD_ENV=cjs
    arch: ppc64le
    before_script: yarn build
    script: yarn test
  - env: TEST_ENV=umd BUILD_ENV=umd
    arch: ppc64le
    before_script:
    # react-router ESM build is imported by react-router-dom UMD,
    # so we need to build it before building react-router-dom UMD
    - cd packages/react-router && BUILD_ENV=esm yarn build && cd -
    - yarn build
    # react-router CJS build is imported by react-router-config tests,
    # so we need to build it before running react-router-config tests
    - cd packages/react-router && BUILD_ENV=cjs yarn build && cd -
    script: yarn test

  - stage: Release
    if: tag =~ ^v[0-9]
    before_script: yarn build
    script: echo "Publishing $TRAVIS_TAG to npm ..."
    before_deploy: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
    deploy:
      provider: script
      skip_cleanup: true
      script: lerna publish from-git --yes --pre-dist-tag next
      on:
        tags: true
  - stage: Deploy Website
    if: branch = website
    env: PUBLIC_PATH=/react-router/
    before_script: yarn build
    script: echo "Deploying website to https://reacttraining.com$PUBLIC_PATH"
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_70c5e56b421c_key -iv $encrypted_70c5e56b421c_iv
      -in website-deploy-key.enc -out website-deploy-key -d
    - chmod 600 website-deploy-key
    - eval $(ssh-agent -s)
    - ssh-add website-deploy-key
    deploy:
      provider: script
      script: bash scripts/deploy-website.sh
      skip_cleanup: true
      on:
        branch: website
