# NOTE: This is based on the original work at https://github.com/elastic/dockerfiles/

cluster.name: "docker-cluster"
network.host: 0.0.0.0
xpack.ml.enabled: false
discovery.seed_hosts: []
bootstrap.system_call_filter: false