name: PR build

on:
  pull_request:
    branches:
      - master
      - replica-master
      
  workflow_dispatch:
    inputs:
      large-runner:
        description: "New Runner to use for failing build"
        required: true
        default: "ubuntu-24.04-ppc64le-2xlarge-p10"
        type: choice
        options:
          - ubuntu-24.04-ppc64le-2xlarge-p10
          - ubuntu-24.04-ppc64le-4xlarge-p10
      pr_number:
        description: "PR number of failing build"
        required: true

run-name: >
  ${{ github.event_name == 'workflow_dispatch'
      && format('PR build for {0} on {1}', inputs.pr_number, inputs.large-runner)
      || format('PR build #{0}', github.event.pull_request.number) }}

jobs:
  validate:
    runs-on: ${{ github.event_name == 'pull_request' && 'ubuntu-24.04-ppc64le-p10' || inputs.large-runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt update -y
          sudo apt-get install -y file

      - name: Install Python dependencies
        run: |
          pip3 install --force-reinstall -v "requests==2.31.0"
          pip3 install --upgrade docker

      - name: Set PR number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number || inputs.pr_number }}" >> $GITHUB_ENV

      - name: Run validate_builds.py script with live logs
        run: |
          python3 -u gha-script/validate_builds.py ${PR_NUMBER:-false} 2>&1 | tee build_log
          my_pid_status=${PIPESTATUS[0]}

          build_size=$(stat -c %s build_log)

          if [ "$my_pid_status" -ne 0 ]; then
            echo "Script failed for PR #${PR_NUMBER}"
            if [ "$build_size" -lt 1800000 ]; then
              cat build_log
            else
              echo "Build log too large, showing last 100 lines"
              tail -100 build_log
            fi
            exit 1
          else
            echo "Script completed successfully for PR #${PR_NUMBER}"
            if [ "$build_size" -lt 1800000 ]; then
              cat build_log
            else
              echo "Build log too large, showing last 100 lines"
              tail -100 build_log
            fi
          fi
